# Plugins

# todo:
  # nodejs
  # python

name: Setup Environment based on ASDF .tool-versions file
description: Setup Environment based on ASDF .tool-versions
inputs:
  asdf_tool_versions_file:
    description: "Path to the asdf tool-versions file"
    default: ".tool-versions"
  golang_action:
    description: "Github action for ASDF plugin: golang"
    default: actions/setup-go@v2
  goreleaser_action:
    description: "Github action for ASDF plugin: goreleaser"
    default: goreleaser-action@v5
  goreleaser_distribution:
    description: "goreleaser (*default) or goreleaser-pro"
    default: goreleaser
  nodejs_action:
    description: "Github action for ASDF plugin: nodejs"
    default: actions/setup-node@v4
  opentofu_action:
    description: "Github action for ASDF plugin opentofu"
    default: opentofu/setup-opentofu@v1
  python_action:
    description: "Github action for ASDF plugin: nodejs"
    default: actions/setup-python@v5
  terraform_action:
    description: "Github action for ASDF plugin: terraform"
    default: hashicorp/setup-terraform@v3


outputs:
  GOLANG_VERSION:
    description: 'golang version'
    value: ${{ steps.setupenv.outputs.GOLANG_VERSION }}
  GORELEASER_VERSION:
    description: 'goreleaser version'
    value: ${{ steps.setupenv.outputs.GORELEASER_VERSION }}
  NODEJS_VERSION:
    description: 'nodejs version'
    value: ${{ steps.setupenv.outputs.NODEJS_VERSION }}
  OPENTOFU_VERSION:
    description: 'opentofu version'
    value: ${{ steps.setupenv.outputs.OPENTOFU_VERSION }}
  PYTHON_VERSION:
    description: 'python version'
    value: ${{ steps.setupenv.outputs.PYTHON_VERSION }}
  TERRAFORM_VERSION:
    description: 'terraform version'
    value: ${{ steps.setupenv.outputs.TERRAFORM_VERSION }}

runs:
  using: "composite"
  steps:
    - name: Setup ASDF environment
      id: setupenv
      shell: bash
      run: |
        touch $INPUT_asdf_tool_versions_file
        cat $INPUT_asdf_tool_versions_file | awk '{printf "%s_VERSION=%s \n",toupper($1),$2 }' >> $GITHUB_OUTPUT
    - name: "asdf-plugin (golang)"
      if: "${{ steps.setupenv.outputs.GOLANG_VERSION != '' }}"
      uses: ${{ inputs.golang_action }}
      with:
        go-version: ${{ steps.setupenv.outputs.GOLANG_VERSION }}
    - name: "asdf-plugin (goreleaser)"
      if: "${{ steps.setupenv.outputs.GORELEASER_VERSION != '' }}"
      uses: ${{ inputs.goreleaser_action }}
      with:
        distribution: ${{ inputs.goreleaser_distribution }}
        version: ${{ steps.setupenv.outputs.GORELEASER_VERSION}}
        install-only: true
    - name: "asdf-plugin (nodejs)"
      if: "${{ steps.setupenv.outputs.NODEJS_VERSION != '' }}"
      uses: ${{ inputs.nodejs_action }}
      with:
          with:
            node-version: ${{ steps.setupenv.outputs.NODEJS_VERSION}}
    - name: "asdf-plugin (opentofu)"
      if: "${{ steps.setupenv.outputs.OPENTOFU_VERSION != '' }}"
      uses: ${{ inputs.opentofu_action }}
      with:
          tofu_version: ${{ steps.setupenv.outputs.OPENTOFU_VERSION}}
    - name: "asdf-plugin (python)"
      if: "${{ steps.setupenv.outputs.NODEJS_VERSION != '' }}"
      uses: ${{ inputs.python_action }}
      with:
        with:
          python-version: ${{ steps.setupenv.outputs.PYTHON_VERSION}}
    - name: "asdf-plugin (terraform)"
      if: "${{ steps.setupenv.outputs.TERRAFORM_VERSION != '' }}"
      uses: ${{ inputs.terraform_action }}
      with:
        with:
          python-version: ${{ steps.setupenv.outputs.TERRAFORM_VERSION}}
